sudo: required
dist: trusty
os: linux
language: minimal
cache:
  directories:
  - depends/built
  - depends/sdk-sources
  - $HOME/.ccache
env:
  global:
    - MAKEJOBS=-j3
    - RUN_TESTS=false
    - CHECK_DOC=0
    - CHECK_LOGPRINT=0
    - BOOST_TEST_RANDOM=1$TRAVIS_BUILD_ID
    - CCACHE_SIZE=100M
    - CCACHE_TEMPDIR=/tmp/.ccache-temp
    - CCACHE_COMPRESS=1
    - BASE_OUTDIR=$TRAVIS_BUILD_DIR/out
    - SDK_URL=https://bitcoincore.org/depends-sources/sdks
    - WINEDEBUG=fixme-all
  matrix:
# ARM
    - HOST=arm-linux-gnueabihf PACKAGES="g++-arm-linux-gnueabihf" CHECK_DOC=1 CHECK_LOGPRINT=1 GOAL="install" BITCOIN_CONFIG="--enable-glibc-back-compat --enable-reduce-exports"
# Win32
    - HOST=i686-w64-mingw32 DPKG_ADD_ARCH="i386" DEP_OPTS="NO_QT=1" PACKAGES="python3 nsis g++-mingw-w64-i686 wine1.6 bc" RUN_TESTS=true GOAL="install" BITCOIN_CONFIG="--enable-reduce-exports"
# 32-bit + dash
    - HOST=i686-pc-linux-gnu PACKAGES="g++-multilib bc python3-zmq" DEP_OPTS="NO_QT=1" RUN_TESTS=true GOAL="install" BITCOIN_CONFIG="--enable-zmq --enable-glibc-back-compat --enable-reduce-exports LDFLAGS=-static-libstdc++" USE_SHELL="/bin/dash" PYZMQ=true
# Win64
    - HOST=x86_64-w64-mingw32 DPKG_ADD_ARCH="i386" DEP_OPTS="NO_QT=1" PACKAGES="python3 nsis g++-mingw-w64-x86-64 wine1.6 bc" RUN_TESTS=true GOAL="install" BITCOIN_CONFIG="--enable-reduce-exports"
# castled
    - HOST=x86_64-unknown-linux-gnu PACKAGES="bc python3-zmq" DEP_OPTS="NO_QT=1 NO_UPNP=1 DEBUG=1" RUN_TESTS=true GOAL="install" BITCOIN_CONFIG="--enable-zmq --enable-glibc-back-compat --enable-reduce-exports CPPFLAGS=-DDEBUG_LOCKORDER" PYZMQ=true
# No wallet
#    - HOST=x86_64-unknown-linux-gnu PACKAGES="python3" DEP_OPTS="NO_WALLET=1" RUN_TESTS=true GOAL="install" BITCOIN_CONFIG="--enable-glibc-back-compat --enable-reduce-exports"
# Cross-Mac
    - HOST=x86_64-apple-darwin11 PACKAGES="cmake imagemagick libcap-dev librsvg2-bin libz-dev libbz2-dev libtiff-tools python-dev" BITCOIN_CONFIG="--enable-gui --enable-reduce-exports" OSX_SDK=10.11 GOAL="deploy"

before_install:
    - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")
install:
    - if [ "$PYZMQ" = "true" ]; then pip install pyzmq --user ; fi
    - if [ -n "$DPKG_ADD_ARCH" ]; then sudo dpkg --add-architecture "$DPKG_ADD_ARCH" ; fi
    - if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get update; fi
    - if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get install --no-install-recommends --no-upgrade -qq $PACKAGES; fi
before_script:
    - if [ "$CHECK_DOC" = 1 ]; then contrib/devtools/check-doc.py; fi
    - if [ "$CHECK_LOGPRINT" = 1 ]; then contrib/devtools/logprint-scanner.py; fi
    - unset CC; unset CXX
    - mkdir -p depends/SDKs depends/sdk-sources
    - if [ -n "$OSX_SDK" -a ! -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then curl --location --fail $SDK_URL/MacOSX${OSX_SDK}.sdk.tar.gz -o depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz; fi
    - if [ -n "$OSX_SDK" -a -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then tar -C depends/SDKs -xf depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz; fi
    - make $MAKEJOBS -C depends HOST=$HOST $DEP_OPTS
script:
    - export TRAVIS_COMMIT_LOG=`git log --format=fuller -1`
    - if [ -n "$USE_SHELL" ]; then export CONFIG_SHELL="$USE_SHELL"; fi
    - OUTDIR=$BASE_OUTDIR/$TRAVIS_PULL_REQUEST/$TRAVIS_JOB_NUMBER-$HOST
    - BITCOIN_CONFIG_ALL="--disable-dependency-tracking --prefix=$TRAVIS_BUILD_DIR/depends/$HOST --bindir=$OUTDIR/bin --libdir=$OUTDIR/lib"
    - depends/$HOST/native/bin/ccache --max-size=$CCACHE_SIZE
    - test -n "$USE_SHELL" && eval '"$USE_SHELL" -c "./autogen.sh"' || ./autogen.sh
    - ./configure --cache-file=config.cache $BITCOIN_CONFIG_ALL $BITCOIN_CONFIG || ( cat config.log && false)
    - make distdir PACKAGE=bitcoin VERSION=$HOST
    - cd bitcoin-$HOST
    - ./configure --cache-file=../config.cache $BITCOIN_CONFIG_ALL $BITCOIN_CONFIG || ( cat config.log && false)
    - make $MAKEJOBS $GOAL || ( echo "Build failure. Verbose build follows." && make $GOAL V=1 ; false )
    - export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/depends/$HOST/lib
    - if [ "$RUN_TESTS" = "true" ]; then travis_wait 30 make $MAKEJOBS check VERBOSE=1; fi
    #- if [ "$RUN_TESTS" = "true" ]; then qa/pull-tester/rpc-tests.py --coverage; fi
after_script:
    - echo $TRAVIS_COMMIT_RANGE
    - echo $TRAVIS_COMMIT_LOG
notifications:
    webhooks: http://travis-hooks.mycryptocoins.net/travis-ci.php
before_deploy:
  - BUILDDIR=build/$TRAVIS_COMMIT/$HOST
  - mkdir -p $BUILDDIR
  - cp -a $OUTDIR/bin $BUILDDIR
  - find $BUILDDIR
deploy:
  - provider: s3
    skip_cleanup: true
    access_key_id: AKIAJXYN32U4M4AWLCXA
    secret_access_key:
      secure: hpm4q6lIobUj7WHSy/9/xTpvLHVJoTIuoM3QcDzXSOM58tD/LKysozG0BOEbAvt4ka29o47bkj49j3wGSOJwmNFPYdpQ1Y/GR4rwhwoOrYkPeQXYw88/lMyoYEeNqcGNkl1JsTTbICjurVhf/gmJZRmQvhg+hnhps5ksTbOX4GwogO3ABORrKeWTNWAwFIpOraFxxVsbK7FAhhc3JdqOegrk58X9d40vOh85f8cu4Jp/yHgT15DSkuDxAkX6+nLb+hMa09sY1UDyvO6WNVmyTQwsVluslUWALDz+bJ6fwGxAn9STV3nDiWyMTy/b/TSZ1sFe9VAzIN/as9R+BUJF4KQ+YJRXAzq9XRK5hh77F338EzdjhUO5ZvgfdMDWdM8Pg5iVGT0Ez8P+k9Zu36x9r8nGIKft9PqhzY61Y6ZfWSuG6hjNV2NnLGjdhGBZ1+hG/PfvOEg3mub+LFHuAUYNuOkpncQzF3hRIIw/DS4+l+XF5FvcPFYBf3eLzWG2wHEaKl4IveJVf+hJs0k0yv55P8znzt89LMTbXxm3KOZTYmH6dR/4rZlKTG++Ag3H3NaI1bC8109LD+x17CsF7AWw/79vtKRl3pRPJ77Ty+nuaxCDmEeUu82jgxr7j6GaSYaklxuIbUhUHOCnZKGwp3QRFq92IiUD5qXSnit1j6lbrE4=
    bucket: coin-build-archive
    region: us-west-2
    local-dir: build
    upload-dir: castle
    acl: public_read
    on:
      branch: master
      repo: MyCryptoCoins/Castle
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: lJqus52v0Sj6sw7lrz4Dogi4uGF6viaoyYVP4zcBHELQeCD1VhcZYr4CAS9VItQkEaTEyLHC3/wRJb1n4bTCt69CIcFd758LTw8Vzq7W5iy9jJqouVvD+qFf82aGh2Hnz/PH52PhQHI3Go4U4XhN99UpOhHCane3sLFNqrTX2hrtXayKzyUQHMuMVZ9xe8DxZFfBSoCyaV82BWpRvON9IZ9aW1y8xlTCA+JWs+djM7csC8lBXnDXC3qnvbWMc7wHoQT0+EUYdaFDGHxctwls5w4NK6GCoSXSeGIYSKVVZ2b2BMV4XqelDvLWUr8XJi2Oz0sNUxHZsHDmu6aHeUVaKBsbBbFOwXxcBMKKx8Xn518u4KCcpsgjM7MySayozheclT9jyOpAGc0nCR+Lg4tJW60p50RfaldpnUZTbvjPKwuREaURLYW8N+yRWng5k/Kr2hTBgWevA6Pb/Be54IDkgVS4JLCeFdwUV3k0du0uGvw2iu3rQiNJgRfEhdPYHpGwrub22KkvUFrQJxP/lJK02wG7xT/juWlAI4Z9XDbpHqsIdwufLn56fbXjvI9zgl1h3XFL3FGwU/OJGCMr5R9tigMJ/djIPH8qWspnfDhbWlcDEbqDK74zEIH698gXoIZatOF6QFmNFTQvQTO5N/3w6JjhD3Sj06CffX9HgFMqP9c=
    file: build/*
    on:
      repo: MyCryptoCoins/Castle
      tags: true
